name: ricky_and_martie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  go_router: ^16.1.0
  provider: ^6.1.5

  flutter_launcher_icons: ^0.14.1 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Configuração do ícone do aplicativo
# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/icon/icon.png"
  min_sdk_android: 21

